### PR TITLE
go away diagram

### PR DESCRIPTION
**Pull request by dnmalenke**
@iCalculated your diagram is beautiful but merge conflicts and double PRs are annoying to deal with

### CODE REVIEW

**Comment by dnmalenke** [comment]
image

**Comment by dnmalenke** [comment]
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by dnmalenke** [comment]
image
image
image
image
image
image
image
image
image
image

**Comment by dnmalenke** [comment]
image
image
image
image
image
image
image
image

**Comment by iCalculated** [comment]
What are double PRs? I think the merge conflict is a relatively minor issue and might be indicative of making too many PRs.

**Comment by dnmalenke** [comment]
> What are double PRs? I think the merge conflict is a relatively minor issue and might be indicative of making too many PRs.

I thought you had to do 2 PRs the other day cause it updated the diagram?
Fair it's a minor inconvenience, but it's pretty annoying to deal with merge conflicts every PR. 
IMO having many PRs does take time, but it lets the group participate a bit more in the project

**Review by e-d-v — APPROVED** [review]

**Pull request merged**
